from __future__ import annotations

from ..models import ExecutionPlan, WorkflowSpec


class GEECompiler:
    def compile(self, workflow: WorkflowSpec, plan: ExecutionPlan) -> tuple[str, list[str]]:
        lines = ["// Generated by GeoMind", f"var workflowName = {workflow.name!r};"]
        explanation: list[str] = []

        for operation in plan.operations:
            if operation.action == "load_local_input":
                geometry = operation.params.get("geometry", "")
                lines.append(f"var roi = ee.FeatureCollection({geometry!r}).geometry();")
                explanation.append("Load ROI geometry as the execution boundary.")
            elif operation.action == "load_dataset":
                dataset_id = operation.params.get("datasetId", "")
                lines.append(f"var collection = ee.ImageCollection('{dataset_id}');")
                explanation.append(f"Load dataset `{dataset_id}`.")
            elif operation.action == "filter_collection":
                lines.append(f"collection = collection.filterDate('{operation.params.get('start')}', '{operation.params.get('end')}').filterBounds(roi);")
                explanation.append("Filter the collection by date range and ROI.")
            elif operation.action == "mask_cloud":
                lines.append("// Cloud mask placeholder")
                explanation.append("Apply cloud masking before compositing.")
            elif operation.action == "temporal_reduce":
                reducer = operation.params.get("reducer", "median")
                lines.append(f"var image = collection.{reducer}().clip(roi);")
                explanation.append(f"Reduce the collection over time with `{reducer}`.")
            elif operation.action == "compute_index":
                index_type = operation.params.get("indexType", "NDVI")
                if index_type == "NDWI":
                    lines.append("var derived = image.normalizedDifference(['B3', 'B8']).rename('NDWI');")
                elif index_type == "NDBI":
                    lines.append("var derived = image.normalizedDifference(['B11', 'B8']).rename('NDBI');")
                else:
                    lines.append("var derived = image.normalizedDifference(['B8', 'B4']).rename('NDVI');")
                explanation.append(f"Compute {index_type} from the current image.")
            elif operation.action == "apply_band_math":
                expression = operation.params.get("expression", "image")
                lines.append(f"var derived = image.expression({expression!r}).rename('BandMath');")
                explanation.append("Apply band math expression to the current image.")
            elif operation.action == "reduce_region":
                reducer = operation.params.get("reducer", "mean")
                lines.extend([
                    "var summary = derived.reduceRegion({",
                    f"  reducer: ee.Reducer.{reducer}(),",
                    "  geometry: roi,",
                    "  scale: 10,",
                    "  maxPixels: 1e13",
                    "});",
                    "print('Summary', summary);",
                ])
                explanation.append(f"Summarize the derived output with reducer `{reducer}`.")
            elif operation.action == "export_result":
                export_format = operation.params.get("format", "GeoTIFF")
                lines.extend([
                    "Map.centerObject(roi, 9);",
                    "Map.addLayer(derived, {}, 'Derived Result');",
                    "Export.image.toDrive({",
                    "  image: derived,",
                    "  description: workflowName,",
                    "  region: roi,",
                    "  scale: 10,",
                    "  maxPixels: 1e13,",
                    f"  fileFormat: '{export_format}'",
                    "});",
                ])
                explanation.append(f"Queue export as `{export_format}`.")

        return "\n".join(lines), explanation
